[package]
name = "center-of-gravity-iced"
version = "0.1.0"
authors = ["Kyle Jones <KyleJonesWinsted@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3.0"
